name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: cd backend && uv sync --all-extras --dev
      - run: cd backend && uv run ruff check src/ tests/ docs/source/ examples/
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: cd backend && uv sync --all-extras --dev
      - run: cd backend && uv run mypy src/ tests/ docs/source/ examples/
  ruff-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: cd backend && uv sync --all-extras --dev
      - run: cd backend && uv run ruff format --check src/ tests/ docs/source/ examples/
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: cd backend && uv sync --all-extras --dev
      - run: cd backend && uv run pytest
  doctest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: cd backend && uv sync --all-extras --dev
      - run: cd backend && uv run make -C docs doctest
